# Generated by Django 5.0.3 on 2024-12-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_kirish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_kirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('haqida', models.TextField()),
                ('rasm', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
