# Generated by Django 5.0.3 on 2024-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shop_kiyimlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_kirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('haqida', models.TextField()),
            ],
        ),
    ]
